# Site settings
title: Anshuman Prasad's Blog
email: anshuman.prasad93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A (mostly) hardware blog by a Duke University student covering a variety of the projects I've undertaken.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  anshu93

# Build settings
markdown: kramdown
